### ISSUE TITLE
How to handle closing animations?

### ISSUE THREAD

**Issue by asnaeb** [desko27/react-call#9]
Libraries like [Radix](https://www.radix-ui.com/primitives/docs/components/dialog) put a data attribute  on their components based on open/closed state so that you can apply css animations accordingly. Whit this library, calling `.end`, causes the component to be immediately unmounted so the only way I can think of to apply closing animations is performing the animation via javascript, then calling `.end` on animation end. Is this how it should be done or am I missing something? 

I really loved the idea behind this library and to use it according to my needs, I ended up writing my own version which is as follows

```typescript
import {ReactNode, useEffect, useState} from "react";

interface Openable<Result> {
  resolve(value?: Result): void;
  state: {
    open: boolean;
    onOpenChange(value: boolean): void;
  };
}

function createOpenable<
  Args = void,
  Result = void,
  Props extends object = object,
>(UserComponent: (args: Props & {openable: Openable<Result>; args: Args}) => ReactNode, timeout = 0) {
  let $resolve: ((value?: Result) => void) | null = null;
  let $setOpen: ((value: boolean) => void) | null = null;
  let $setArgs: ((value: Args) => void) | null = null;

  return {
    Component(props: Props) {
      const [open, setOpen] = useState(false);
      const [args, setArgs] = useState({} as Args);

      useEffect(() => {
        $setOpen = setOpen;
        $setArgs = setArgs;
        return () => {
          $setOpen = null;
          $setArgs = null;
          $resolve = null;
        };
      }, []);

      const openable: Openable<Result> = {
        state: {
          open,
          onOpenChange(value) {
            if (!value) {
              $resolve?.();
              setTimeout(setArgs.bind(null, {} as Args), timeout);
            }
            setOpen(value);
          }
        },
        resolve(value: Result) {
          if (typeof $resolve !== "function") {
            throw Error();
          }
          $resolve(value);
          setOpen(false);
          setTimeout(setArgs.bind(null, {} as Args), timeout);
        }
      };

      return <UserComponent {...props} openable={openable} args={args as Args}/>;
    },
    open(args: Args) {
      if (typeof $setOpen !== "function") {
        throw Error();
      }
      if (args) {
        if (typeof $setArgs !== "function") {
          throw Error();
        }
        $setArgs(args);
      }
      $setOpen(true);
      return new Promise<Result | undefined>(resolve => $resolve = resolve);
    }
  };
}

export {createOpenable};
```
I don't need the component to stack, nor to be unmounted but I just want to open and close it imperatively. I would love to know if there are plans to support such a thing and if I can make anything to contribute!

**Comment by desko27** [comment]
I've published `react-call@next` as a pre-release for testing purposes. Could you please give it a try and let me know?

Of course, any idea on how to reduce the bundle size is more than welcome!

**Comment by asnaeb** [comment]
I tested it and I've been able to achieve what I wanted by setting the delay to the animation duration. A minimal example using Radix Dialog component would be
```tsx
import * as Dialog from "@radix-ui/react-dialog"

const CallableDialog = createCallable(({call}) => (
  <Dialog.Root open={!call.ended} onOpenChange={value => !value && call.end()}>
    <Dialog.Content className="data-[state=closed]:animate-my-animation">
      <button onClick={() => call.end()}>close</button>
    <Dialog.Content>
  </Dialog.Root>
), 200)
```
Setting a delay was the same conclusion I had thought of so looks good to me. Plus, I don't think that 500 or 550B would be that much of a difference honestly.

**Comment by desko27** [comment]
This will get delivered in v1.3.0. @asnaeb thanks for contributing!!
